---

# -----------------------------------------------------------------------------
# File        : ctlabs-terraform/03_bigquery/config.yml
# Description : main configuration to provision bigquery 
# -----------------------------------------------------------------------------

defaults:
  bigquery:
    datasets:
      destroy: true
      location: us-east1
      labels:
        owner  : me
        project: project_1
    tables:
      labels:
        owner  : me
        project: project_1

bigquery:
  # ---------------------------------------------------------------------------
  # DATASET employees_db
  # ---------------------------------------------------------------------------
  employees_db:
    friendly : sample employees database
    desc     : "a sample database: https://www3.ntu.edu.sg/home/ehchua/programming/sql/SampleDatabases.html"
    destroy  : true
    location : us-east1
    labels   :
      owner: analysts
    access:
      - role   : roles/bigquery.user
        members:
          - "group:devs@acedxo.com"
      - role   : roles/bigquery.dataViewer
        members:
          - "group:finance-and-accounting@acedxo.com"
          - "group:devs@acedxo.com"
    tables:
      - name: employees
        access:
          - role   : roles/bigquery.dataViewer
            members:
              - "group:new-group@acedxo.com"
        labels:
          owner: michael
        schema:
          - { name: emp_no,     type: INTEGER }
          - { name: birth_date, type: DATE    }
          - { name: first_name, type: STRING  }
          - { name: last_name,  type: STRING  }
          - { name: gender,     type: STRING  }
          - { name: hire_date,  type: DATE    }
        constraints:
          primary_key: [ emp_no ]
      - name: departments
        access: []
        labels:
        schema:
          - { name: dept_no,   type: STRING }
          - { name: dept_name, type: STRING }
        constraints:
          primary_key: [ dept_no ]
      - name: dept_emp
        access: []
        labels:
        schema:
          - { name: emp_no,    type: INTEGER }
          - { name: dept_no,   type: STRING  }
          - { name: from_date, type: DATE    }
          - { name: to_date,   type: DATE    }
        constraints:
          primary_key: [ emp_no, dept_no ]
      - name: dept_manager
        access: []
        labels:
        schema:
          - { name: dept_no,   type: STRING  }
          - { name: emp_no,    type: INTEGER }
          - { name: from_date, type: DATE    }
          - { name: to_date,   type: DATE    }
        constraints:
          primary_key: [ emp_no, dept_no ]
      - name: title
        access: []
        labels:
        schema:
          - { name: emp_no,    type: INTEGER }
          - { name: title,     type: STRING  }
          - { name: from_date, type: DATE    }
          - { name: to_date,   type: DATE    }
        constraints:
          primary_key: [ emp_no, title, from_date ]
      - name: salaries
        labels:
        schema:
          - { name: emp_no,    type: INTEGER }
          - { name: salary,    type: INTEGER }
          - { name: from_date, type: DATE    }
          - { name: to_date,   type: DATE    }
        constraints:
          primary_key: [ emp_no, from_date ]

  # ---------------------------------------------------------------------------
  # DATASET basic_bq
  # ---------------------------------------------------------------------------
  basic_bq:
    friendly: foo
    destroy: true
    location: us-east1
    access: []
    labels:
      owner: dba
    tables:
      - name: bar
        access: []
        labels:
          env      : devops
          billable : true
          owner    : janesmith
        schema:
          - { name: fullVisitorId,  type: STRING  }
          - { name: visitNumber,    type: INTEGER }
          - { name: visitId,        type: INTEGER }
          - { name: visitStartTime, type: INTEGER }
          - { name: fullDate,       type: DATE    }
