---

# -----------------------------------------------------------------------------
# File        : ctlabs-terraform/02_buckets/config.yml
# Description : main configuration to provision buckets
# -----------------------------------------------------------------------------

# The project gets imported from the file ctlabs-terraform/gcp.conf.yml 
# which has the following format:
# 
#project:
#  name         : 02-CtLabs Cloud Functions LAB
#  id           : <GCP_PROJECT_ID>
#  oid          : <GCP_ORGANIZATION_ID>
#  user         : <GCP_USER>
#  billing      : <GCP_BILLING_ACCOUNT_ID>
#  vpc_type     : regular # shared, service
#  shared_vpc   : <GCP_PROJECT_ID> of host project (only used when vpc_type == service)
#  sa_delete    : true
#  region       : <gcp_region>
#  zone         : <gcp_zone>
#  labels       :
#    ctlabs : secrets_lab
#


# -----------------------------------------------------------------------------
#
# YAML DEFAULTS
#
defaults:
  labels: &default_labels
    ctlabs_created : true
    owner          : ctlabs_admin
  spot: &default_spot
    action  : STOP
    lifespan: 2 # in hours
  disks: &default_disks
    boot:
# -----------------------------------------------------------------------------

services:
  - compute.googleapis.com
  - cloudfunctions.googleapis.com
  - cloudbuild.googleapis.com
  - artifactregistry.googleapis.com

buckets:
  - name     : ctlabs_bucket_functions
    location : us

functions:
  - name     : hello_http
    desc     : a test cloud function
    runtime  : python39
    mem      : 128                       # min mem = 128
    bucket   : ctlabs_bucket_functions
    object   : hello_http
    source   : hello_func/hello_http.zip
    http     : true
    entry    :
    labels   : *default_labels
    env_vars :

network:
  - name: net1

subnet: 
  net1:
    - name : net1-lan2
      cidr : 192.168.67.0/24

vms: 
  - name     : vm-1
    type     : e2-micro
    image    : centos-stream-9-v20240213
    net      : net1-lan2
    spot     : *default_spot
    disks    : *default_disks
    labels   : *default_labels

firewall:
  net1:
    ingress: []
    egress : []
