---

# -----------------------------------------------------------------------------
# File        : ctlabs-terraform/05a_shared-vpc/config.yml
# Description : main configuration to provision shared vpc host project
# -----------------------------------------------------------------------------

# The project gets imported from the file ctlabs-terraform/gcp.conf.yml 
# which has the following format:
# 
#project:
#  name         : 02-CtLabs Cloud Functions LAB
#  id           : <GCP_PROJECT_ID>
#  oid          : <GCP_ORGANIZATION_ID>
#  user         : <GCP_USER>
#  billing      : <GCP_BILLING_ACCOUNT_ID>
#  vpc_type     : regular # shared, service
#  shared_vpc   : <GCP_PROJECT_ID> of host project (only used when vpc_type == service)
#  sa_delete    : true
#  region       : <gcp_region>
#  zone         : <gcp_zone>
#  labels       :
#    ctlabs : secrets_lab
#

# -----------------------------------------------------------------------------
#
# YAML DEFAULTS
#
defaults:
  labels: &default_labels
    ctlabs_created : true
    owner          : ctlabs_admin
  spot: &default_spot
    action  : STOP
    lifespan: 8 # in hours
  disks: &default_disks
    boot:
    acedxo:
    dump:
# -----------------------------------------------------------------------------

services:
  - iam.googleapis.com
  - cloudresourcemanager.googleapis.com
  - secretmanager.googleapis.com
  - dns.googleapis.com

dns:
  ctlabs-internal:
    domain  : ctlabs.internal
    desc    : ctlabs internal dns zone
    labels  : *default_labels
    networks:
      - net1
      - net2
    records:
      - name : ns1.ctlabs.internal
        type : NS
        value: 172.25.70.2

network:
  - name : net1
  - name : net2

subnet:
  net1:
    - name : net1-lan1
      cidr : 172.25.70.0/24
  net2:
    - name : net2-lan1
      cidr : 172.25.71.0/24

firewall:
  net1:
    ingress:
      - name   : net1-ssh-iap
        ports  : [22]
        src    : [35.235.240.0/20]

      - name   : net1-ctlabs-in
        ports  : [80,443,3000,4567,8080,8081,8082,8090,8200,8300,8443]
        src    : [0.0.0.0/0]

    egress:
      - name   : net1-deny-all
        proto  : all
        dst    : [0.0.0.0/0]
        prio   : 5000
        action : deny

      - name   : net1-default-tcp
        ports  : [22,53,80,443,8200]
        dst    : [0.0.0.0/0]

      - name   : net1-default-udp
        proto  : udp
        ports  : [53,123,1194]
        dst    : [0.0.0.0/0]

      - name   : net1-default-icmp
        proto  : icmp
        dst    : [0.0.0.0/0]

  net2:
    ingress:
      - name   : net2-ssh-iap
        ports  : [22]
        src    : [35.235.240.0/20]

    egress:
      - name   : net2-deny-all
        proto  : all
        dst    : [0.0.0.0/0]
        prio   : 5000
        action : deny

      - name   : net2-default-tcp
        ports  : [22,53,80,443]
        dst    : [0.0.0.0/0]

      - name   : net2-default-udp
        proto  : udp
        ports  : [53,123,1194]
        dst    : [0.0.0.0/0]

      - name   : net2-default-icmp
        proto  : icmp
        dst    : [0.0.0.0/0]

#buckets:
#  - name     : tf-state
#    location : us-east1
#    destroy  : true
#    labels   : *default_labels
