---

# -----------------------------------------------------------------------------
# File        : ctlabs-terraform/secrets/config.yml
# Description : main configuration to provision secrets
# -----------------------------------------------------------------------------

# The project gets imported from the file ctlabs-terraform/gcp.conf.yml
# which has the following format:
#
#project:
#  id     : <GCP_PROJECT_ID>
#  user   : <GCP_USER>
#  region : <GCP_REGION>
#  zone   : <GCP_ZONE>
#

# -----------------------------------------------------------------------------
#
# YAML DEFAULTS
#
defaults:
  labels: &default_labels
    ctlabs_created : true
    owner          : ctlabs_admin
  spot: &default_spot
    action  : STOP
    lifespan: 8 # in hours
  disks: &default_disks
    boot:
# -----------------------------------------------------------------------------

services:
  - compute.googleapis.com
  - secretmanager.googleapis.com
  - iam.googleapis.com
  - cloudresourcemanager.googleapis.com

network:
  - name : net1
  - name : net2

subnet:
  net1:
    - name : net1-lan1
      cidr : 172.25.70.0/24
  net2:
    - name : net2-lan1
      cidr : 172.25.71.0/24

firewall:
  net1:
    ingress:
      - name   : net1-ssh-iap
        ports  : [22]
        src    : [35.235.240.0/20]

      - name   : net1-ctlabs-in
        ports  : [80,443,3000,4567,8080,8081,8082,8090,8200,8300,8443]
        src    : [0.0.0.0/0]

    egress:
      - name   : net1-deny-all
        proto  : all
        dst    : [0.0.0.0/0]
        prio   : 5000
        action : deny

      - name   : net1-default-tcp
        ports  : [22,53,80,443]
        dst    : [0.0.0.0/0]

      - name   : net1-default-udp
        proto  : udp
        ports  : [53,123,1194]
        dst    : [0.0.0.0/0]

      - name   : net1-default-icmp
        proto  : icmp
        dst    : [0.0.0.0/0]

  net2:
    ingress:
      - name   : net2-ssh-iap
        ports  : [22]
        src    : [35.235.240.0/20]

    egress:
      - name   : net2-deny-all
        proto  : all
        dst    : [0.0.0.0/0]
        prio   : 5000
        action : deny

      - name   : net2-default-tcp
        ports  : [22,53,80,443]
        dst    : [0.0.0.0/0]

      - name   : net2-default-udp
        proto  : udp
        ports  : [53,123,1194]
        dst    : [0.0.0.0/0]

      - name   : net2-default-icmp
        proto  : icmp
        dst    : [0.0.0.0/0]

buckets:
  - name     : named-mason-414305_tf-state
    location : us
    destroy  : true
    labels   : *default_labels

vms:
  - name     : vm-1
    type     : e2-medium
    image    : centos-stream-9-v20240213
    #image   : debian-11-bullseye-v20240213
    net      : net1-lan1
    script   : ./ppvm.sh
    spot     : *default_spot
    nat      : true
    disks    : 
      <<: *default_disks
      vg-data-1:
    labels   :
      <<    : *default_labels
      ctlabs: service_account_given
    service_account :
      email : 611455190411-compute@developer.gserviceaccount.com
      scopes: ["cloud-platform"]

  - name     : vm-2
    type     : e2-micro
    #image    : centos-stream-9-v20240213
    image    : debian-11-bullseye-v20240213
    net      : net1-lan1
    nat      : true
    spot     : *default_spot
    disks    : *default_disks
    labels   :
      <<    : *default_labels
      ctlabs: no_service_account

  - name     : vm-3
    type     : e2-micro
    #image    : centos-stream-9-v20240213
    image    : debian-12-bookworm-v20240910
    net      : net2-lan1
    nat      : true
    spot     : *default_spot
    disks    : *default_disks
    labels   :
      <<    : *default_labels
      ctlabs: no_service_account

#  - name       : vm-2
#    type       : n2-highcpu-4
#    image      : centos-stream-9-v20240213
#    #image      : debian-11-bullseye-v20240213
#    net        : net1-lan1
#    script     : ../ppvm.sh
#    spot       :
#      lifespan   : 6 # in hours
#    nested     : true
#    nat        : true
#    labels     :
#      ctlabs: riscv6
