---

# -----------------------------------------------------------------------------
# File        : ctlabs-terraform/lpic2/config.yml
# Description : main configuration to provision lpic2 
# -----------------------------------------------------------------------------

# The project gets imported from the file ctlabs-terraform/gcp.conf.yml 
# which has the following format:
# 
#project:
#  id     : <GCP_PROJECT_ID>
#  user   : <GCP_USER>
#  region : <GCP_REGION>
#  zone   : <GCP_ZONE>
#

# -----------------------------------------------------------------------------
#
# YAML DEFAULTS
#
defaults:
  labels: &default_labels
    ctlabs : lpic2
    owner  : ctlabs_admin
  spot: &default_spot
    action  : STOP
    lifespan: 2 # in hours
  disks: &default_disks
    boot:
# -----------------------------------------------------------------------------

services:
  - secretmanager.googleapis.com

network:
  - name : net1

subnet:
  net1:
    - name : net1-lan1
      cidr : 172.25.70.0/24

firewall:
  net1:
    ingress:
      - name   : net1-ssh-iap
        proto  : tcp
        ports  : [22]
        src    : [35.235.240.0/20]

      - name   : net1-ctlabs-in
        proto  : tcp
        ports  : [80,443,3000,4567,8080,8081,8082,8090,8443]
        src    : [0.0.0.0/0]

    egress:
      - name   : net1-deny-all
        proto  : all
        dst    : [0.0.0.0/0]
        prio   : 5000
        action : deny

      - name   : net1-default-tcp
        proto  : tcp
        ports  : [22,53,80,443]
        dst    : [0.0.0.0/0]

      - name   : net1-default-udp
        proto  : udp
        ports  : [53,123,1194]
        dst    : [0.0.0.0/0]

      - name   : net1-default-icmp
        proto  : icmp
        ports  : []
        dst    : [0.0.0.0/0]
        
vms:
  - name       : vm-1
    type       : e2-medium
    #image      : ctlabs-2024-04-25
    image      : centos-stream-9-v20240213
    #image      : debian-11-bullseye-v20240213
    net        : net1-lan1
    #script     : ../ppvm.sh
    spot       : *default_spot
    disks      : *default_disks
    labels     : *default_labels

#  - name       : vm-2
#    type       : e2-medium
#    image      : image-1
#    net        : net1-lan1
#    nat        : true
#    spot       : *default_spot
#    labels     : *default_labels


#  - name       : vm-2
#    type       : n2-highcpu-4
#    image      : centos-stream-9-v20240213
#    #image      : debian-11-bullseye-v20240213
#    net        : net1-lan1
#    nat        : true
#    nested     : true
#    script     : ../ppvm.sh
#    spot       : *default_spot
#    labels     : *default_labels
